### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by rpuckett** [aar/imis_sso#1]
Last week I could log in as myself with the IMIS button, but now, I am getting a 500 error at https://qa-papers7.aarweb.org/admin/config/people/imis-redirect:

This page isn’t working
qa-papers7.aarweb.org is currently unable to handle this request.
HTTP ERROR 500

**Comment by rpuckett** [comment]
I changed my password in iMIS if that makes any difference.

**Comment by huntaw** [comment]
I made a small change to it. I am trying to track down the bug now

**Comment by huntaw** [comment]
Try now

**Comment by rpuckett** [comment]
Yes, that worked!
