### ISSUE TITLE
If user has a Guest account in PAPERS with the same email address as iMIS, cannot log in

### ISSUE THREAD

**Issue by rpuckett** [aar/imis_sso#3]
Testing with S. Jonathan O'Donnell, sjodonnell@gmail.com

Notice: Undefined variable: mail in imis_sso_login_user() (line 179 of /srv/www/qa.papers7.aarweb.org/htdocs/sites/all/modules/contrib/imis_sso/imis_sso.module).
iMIS Login failed. A User with your email exists in the system already. Please contact the site admin.

**Comment by rpuckett** [comment]
Guest account is https://qa-papers7.aarweb.org/user/5503/edit

**Comment by StevenJayGilbert** [comment]
@rpuckett can you give me the iMIS test login for this user? The notice Undefined variable is a bug. But in general you are correct. If the email is in use in Papers and the person has not logged in yet through a SSO then they can't log in using an existing email. This is a security issue. Otherwise anyone who wanted to log in as a user could just change their email in iMIS then log in and they would assume the identity of the member. Make sense?

**Comment by StevenJayGilbert** [comment]
In a world where I had more time we would ask the user to verify the email then log them in

**Comment by rpuckett** [comment]
Not sure what you mean by iMIS test login. The email is sjodonnell@gmail.com and the iMIS ID is 5503.

I do see the security issue. But if only staff are changing the iMIS usernames, they could check the email against the iMIS database (and maybe the PAPERS database too.)

This whole thing is another example of why having Guest accounts in PAPERS at all is a terrible idea.

**Comment by rpuckett** [comment]
Sorry - the PAPERS ID was 5503. iMIS ID is 24535.

**Comment by StevenJayGilbert** [comment]
Ha I agree. We tried to prevent it. I mean the password used for that account. One thing that might help in the future is to add a check on the guest account creation to see if the email is in use on iMIS. If it is ask the use creating the guest account if they meant for it to be that user. That might help cut down more on the duplicate guest accounts.

**Comment by StevenJayGilbert** [comment]
I would have to write code to email someone every time a member logged in using their email to sync rather than their account. It is a security hole no matter what so I would want Alice's approval before doing that

**Comment by rpuckett** [comment]
All the test account passwords right now are just AARweb123 .

**Comment by rpuckett** [comment]
I like the idea of the check against iMIS for Guest account creation. Could we employ a similar strategy with the Guest accounts in the system now?

**Comment by StevenJayGilbert** [comment]
I could write a back end that would grab all the iMIS users based on the guest account email and display that next to the name of the guest account with a checkbox to sync them. Is that what you had in mind?

**Comment by rpuckett** [comment]
That's a better solution than what I had in mind which was just running a check of all guest account emails vs. iMIS emails and manually merging their accounts.

**Comment by StevenJayGilbert** [comment]
Sounds like we could use three features. One is a feature request for the SSO login to validate an email if it is in use. The other two are Papers features. Back end for sync and a front end to ask the member creating the guest account. Can you add them as separate github issues so we can prioritize

**Comment by rpuckett** [comment]
Add them on the PAPERS repository?

**Comment by StevenJayGilbert** [comment]
Add the validation of the email when a user logs in rather than the contact the admin here. This module is used for ES and possibly others and that would be useful for all. The other two on papers

**Comment by rpuckett** [comment]
I think you might be able to describe the issue better than I can - Can you create them and then I will prioritize?

**Comment by StevenJayGilbert** [comment]
Ok

**Comment by StevenJayGilbert** [comment]
I have fixed the issue that was throwing the undefined notice warning. The main issue of not being able to log in if the email already exists is working as expected. Please check that the warning is not being thrown anymore. I added issue #4 as a possible improvement to the current error message.

**Comment by rpuckett** [comment]
On retest, the error is just: 

iMIS Login failed. A User with your email exists in the system already. Please contact the site admin.

No undefined variable.

**Comment by StevenJayGilbert** [comment]
That is working as expected. If issue #4 works as a UI improvement over the error as well as the possibility of linking the existing guest accounts then lets close this. Otherwise we can talk about other possible solutions.

**Comment by rpuckett** [comment]
Yes, closing.
